name: Doc Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Install AI2Business
        run: |
          pip install -e .
      - name: Set git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Build documentation
        run: |
          cd docs
          pip install -r doc-requirements.txt
          python autogen.py
          mkdocs build