name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker tag DOCKER_ID:$(date +%s) docker.pkg.github.com/AI2Business/ai2business/DOCKER_AI2BUSINESS:$(date +%s)
        docker build -t docker.pkg.github.com/AI2Business/ai2business/DOCKER_AI2BUSINESS:$(date +%s) . --file Dockerfile
        docker push docker.pkg.github.com/AI2Business/ai2business/DOCKER_AI2BUSINESS:$(date +%s)
