name: Python docs
on:
  push:
    branches: [master, main]

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
          pip install -e .
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version